### ISSUE TITLE
german-accents gets removed

### ISSUE THREAD

**Issue by TheAlgorythm** [federico-terzi/espanso-hub-core#2]
I'm on v0.7.3 and everytime I want to insert a German accent it gets removed on my Manjaro Linux system.
This happens everywhere (e.g. Firefox, Kate) besides Alacrity.
The weird thing is: other plugins (lorem, espanso-latex) work fine.
The log seems fine.

**Comment by federico-terzi** [comment]
Hey @TheAlgorythm,

I'm sorry you experienced this problem! Could you please try upgrading to version 2 and see if the problem persists? More info here: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by TheAlgorythm** [comment]
v2 seems to work.
Thank you for the great software, which helps me, as a handicapped person in IT a lot.

**Comment by federico-terzi** [comment]
@TheAlgorythm Thanks! Really glad Espanso is helping you :)
